---

- name: install mongodb
  yum: name=mongodb,mongodb-server disablerepo=* enablerepo=fedora,updates state=present
  tags: mongodb

- name: Create database folder
  file: path={{mongodb.db}} group=mongodb owner=mongodb mode=755 state=directory
  tags: mongodb

- name: Create log folder
  file: path=/var/log/mongo group=mongodb owner=mongodb mode=755 state=directory
  tags: mongodb

- name: configure mongodb
  template: src=mongodb.conf.j2 group=mongodb owner=mongodb mode=755 dest=/etc/mongodb.conf
  tags: mongodb

- name: run mongodb
  service: name=mongod state=started enabled=yes
  tags: mongodb

- name: copy backup script
  template: src=backup.sh dest=/root/backup.sh mode=755

- name: copy backup env
  template: src=env dest=/root/env mode=755

- name: add cron job
  cron: name="back up mongodb" minute="0" hour="10,17" job="sh /root/backup.sh"
