---

- name: install mongodb
  yum: name=mongodb,mongodb-server disablerepo=* enablerepo=fedora,updates state=present
  tags: mongodb

- name: Create database folder
  file: path={{mongodb.db}} group=mongodb owner=mongodb mode=755 state=directory
  tags: mongodb

- name: Create log folder
  file: path=/var/log/mongo group=mongodb owner=mongodb mode=755 state=directory
  tags: mongodb

- name: configure mongodb
  template: src=mongodb.conf.j2 group=mongodb owner=mongodb mode=755 dest=/etc/mongodb.conf
  tags: mongodb

- name: enable firewalld
  service: name=firewalld state=started enabled=yes

- name: open port 27017
  shell: firewall-cmd --permanent --zone=public --add-port=27017/tcp
  tags: mongodb

- name: open port 28017 (web console)
  shell: firewall-cmd --permanent --zone=public --add-port=28017/tcp
  tags: mongodb

- name: open port 27017 immediately
  shell: firewall-cmd --permanent --add-port=27017/tcp
  tags: mongodb

- name: open port 28017 (web console) immediately
  shell: firewall-cmd --zone=public --add-port=28017/tcp
  tags: mongodb

- name: run mongodb
  service: name=mongod state=started enabled=yes
  tags: mongodb
