---
- hosts: app
  vars_files:
    - vars.yml

  tasks:
    - name: Add Epel repo
      yum:
        name: epel-release
        state: present

    - name: Install yum packages
      yum: name={{item}} state=latest
      with_items:
        - make
        - automake
        - gcc
        - gcc-c++
        - kernel-devel
        - git
        - nodejs
        - npm
        - nginx

    - name: Disable ssh password login
      lineinfile: dest=/etc/ssh/sshd_config state=present regexp='^(\s+)?#?(\s+)?PasswordAuthentication(\s+)?(no|yes)' line='PasswordAuthentication no'
    - name: restart sshd
      service: name=sshd state=restarted

    - name: install n (node version installer/switcher)
      npm: name=n state=present global=yes

    - name: install the latest stable version of node
      shell: n stable

    - name: Create web user
      user: name=web

    - name: Create project folder
      file: path=/var/www group=web owner=web mode=755 state=directory

    - name: Copy local env file
      template: src=templates/env.j2 dest=/var/www/env

    - name: enable firewalld
      service: name=firewalld state=started enabled=yes

    - name: open port 3000
      shell: firewall-cmd --permanent --zone=public --add-port=3000/tcp
    - name: open port 3000 for current session
      shell: firewall-cmd --zone=public --add-port=3000/tcp

    - name: Add systemd conf
      template: src=templates/systemd.service.j2 dest=/etc/systemd/system/{{project_name}}-web.service
      notify:
        - enable {{project_name}}-web

  handlers:
    - name: enable {{project_name}}-web
      shell: systemctl enable {{project_name}}-web
