---
- hosts: mongodb
  vars_files:
    - vars.yml

  tasks:
    - name: Disable ssh password login
      lineinfile: dest=/etc/ssh/sshd_config state=present regexp='^#?PasswordAuthentication no' line='PasswordAuthentication no'
    - name: restart sshd
      service: name=sshd state=restarted

    - name: enable firewalld
      service: name=firewalld state=started enabled=yes

    - name: set default zone to trusted
      shell: firewall-cmd --set-default-zone=trusted

    - name: open port 27017
      shell: firewall-cmd --permanent --zone=trusted --add-port=27017/tcp

    # - name: open port 28017 (web console)
    #   shell: firewall-cmd --permanent --zone=trusted --add-port=28017/tcp

    - name: whitelist app servers
      shell: firewall-cmd --permanent --zone=trusted --add-source={{ item }}/32
      with_items: groups['app']

    - name: restart firewalld
      shell: firewall-cmd --reload

  roles:
    - mongodb
